from django.urls import path, include, re_path

from .views import (
    TeacherListAPIView,
    TeacherRetrieveUpdateAPIView,
    InfoFormListAPIView,
    UserCourseListAPIView,
    ApplyCourseListAPIView,
    FeedbackFormListAPIView,
    FeedbackFormRetrieveAPIView,
    FeedbackUnitListAPIView,
    FeedbackUnitRetrieveAPIView,
    FeedbackPicAPIListView,
    FeedbackPicRetrieveAPIView,
    NoProtocalListAPIView,
    NoFeedbackListAPIView,
    NoAllFeedbackListAPIView,
    IsAllFeedbackListAPIView,
    NoFinishCourseListAPIView,
    FinishCourseListAPIView,
    SearchUserCourseListAPIView,
    UserCourseUpdateAPIView,
    FeedbackPicCollectListAPIView,
    FeedbackPicLikeListAPIView,
    FeedbackPicLikeUpdateAPIView,
    CountApplyDataListAPIView,
    ShareListAPIView,
)

urlpatterns = [
    path(
        'list/',
        TeacherListAPIView.as_view()
    ),
    path(
        'detail/<int:pk>/',
        TeacherRetrieveUpdateAPIView.as_view()
    ),
    path(
        'info_form/',
        InfoFormListAPIView.as_view()
    ),
    path(
        'user_course/',
        UserCourseListAPIView.as_view()
    ),
    path(
        'apply_course/',
        ApplyCourseListAPIView.as_view()
    ),
    path(
        'feedback_form/',
        FeedbackFormListAPIView.as_view()
    ),
    path(
        'feedback_form_detail/<int:pk>',
        FeedbackFormRetrieveAPIView.as_view()
    ),
    path(
        'feedback_unit/',
        FeedbackUnitListAPIView.as_view()
    ),
    path(
        'feedback_unit_detail/<int:pk>',
        FeedbackUnitRetrieveAPIView.as_view()
    ),
    path(
        'feedback_pic/',
        FeedbackPicAPIListView.as_view()
    ),
    path(
        'feedback_pic_detail/<int:pk>',
        FeedbackPicRetrieveAPIView.as_view()
    ),
    re_path(
        r'^no_protocal_list/(?P<term>.+)/$',
        NoProtocalListAPIView.as_view()
    ),
    re_path(
        r'^no_feedback_list/(?P<term>.+)/$',
        NoFeedbackListAPIView.as_view()
    ),
    re_path(
        r'^no_all_feedback_list/(?P<term>.+)/$',
        NoAllFeedbackListAPIView.as_view()
    ),
    re_path(
        r'is_all_feedback_list/(?P<term>.+)/$',
        IsAllFeedbackListAPIView.as_view()
    ),
    re_path(
        r'no_finish_course_list/(?P<term>.+)/$',
        NoFinishCourseListAPIView.as_view()
    ),
    re_path(
        r'finish_course_list/(?P<term>.+)/$',
        FinishCourseListAPIView.as_view()
    ),
    re_path(
        r'search_usercourse/(?P<keyword>.+)/(?P<term>.+)/(?P<tag>.+)/$',
        SearchUserCourseListAPIView.as_view()
    ),
    path(
        'update_usercourse/<int:pk>',
        UserCourseUpdateAPIView.as_view()
    ),
    re_path(
        r'feedback_pic_collect/(?P<endDate>.+)/(?P<startDate>.+)/$',
        FeedbackPicCollectListAPIView.as_view()
    ),
    re_path(
        r'feedback_pic_like/(?P<endDate>.+)/(?P<startDate>.+)/$',
        FeedbackPicLikeListAPIView.as_view()
    ),
    path(
        'feedback_pic_like_update/<int:pk>',
        FeedbackPicLikeUpdateAPIView.as_view()
    ),
    re_path(
        r'count_apply_data/(?P<term>.+)/(?P<tag>.+)/$',
        CountApplyDataListAPIView.as_view()
    ),
    re_path(
        r'share_list/(?P<endDate>.+)/(?P<startDate>.+)/$',
        ShareListAPIView.as_view()
    ),
]
