from django.urls import path, include, re_path

from .views import (
    TeacherListAPIView,
    TeacherRetrieveUpdateAPIView,
    InfoFormListAPIView,
    UserCourseListAPIView,
    ApplyCourseListAPIView,
    FeedbackFormListAPIView,
    FeedbackUnitListAPIView,
    FeedbackUnitRetrieveAPIView,
    FeedbackPicAPIListView,
    FeedbackPicRetrieveAPIView,
    FeedbackImageAllListAPIView,
    FeedbackImageLikeListAPIView,
    FeedbackImageLikeUpdateAPIView,
    ShareGraphicAllListAPIView,
    ShareGraphicLikeListAPIView,
    ShareGraphicLikeUpdateAPIView,
    UserCourseListAPIView,
    UserCourseItemUpdateAPIView,
    UserCourseRemarksCreateAPIView,
    UserCourseRemarksDestroyAPIView,
    UserCourseRemarksRetrieveAPIView,
    ApplyCourseRetrieveAPIView,
    FeedbackFormRetrieveAPIView,
    TeacherInfoFormRetrieveAPIView,
)

urlpatterns = [
    path(
        'list/',
        TeacherListAPIView.as_view()
    ),
    path(
        'detail/<int:pk>/',
        TeacherRetrieveUpdateAPIView.as_view()
    ),
    path(
        'info_form/',
        InfoFormListAPIView.as_view()
    ),
    path(
        'user_course/',
        UserCourseListAPIView.as_view()
    ),
    path(
        'apply_course/',
        ApplyCourseListAPIView.as_view()
    ),
    path(
        'feedback_form/',
        FeedbackFormListAPIView.as_view()
    ),
    path(
        'feedback_unit/',
        FeedbackUnitListAPIView.as_view()
    ),
    path(
        'feedback_unit_detail/<int:pk>',
        FeedbackUnitRetrieveAPIView.as_view()
    ),
    path(
        'feedback_pic/',
        FeedbackPicAPIListView.as_view()
    ),
    path(
        'feedback_pic_detail/<int:pk>',
        FeedbackPicRetrieveAPIView.as_view()
    ),
    re_path(
        r'feedback_image_all_list/(?P<endDate>.+)/(?P<startDate>.+)/$',
        FeedbackImageAllListAPIView.as_view()
    ),
    re_path(
        r'feedback_image_like_list/(?P<endDate>.+)/(?P<startDate>.+)/$',
        FeedbackImageLikeListAPIView.as_view()
    ),
    path(
        'feedback_pic_like_update/<int:pk>',
        FeedbackImageLikeUpdateAPIView.as_view()
    ),
    re_path(
        r'share_graphic_all_list/(?P<endDate>.+)/(?P<startDate>.+)/$',
        ShareGraphicAllListAPIView.as_view()
    ),
    re_path(
        r'share_graphic_like_list/(?P<endDate>.+)/(?P<startDate>.+)/$',
        ShareGraphicLikeListAPIView.as_view()
    ),
    path(
        'share_graphic_like_update/<int:pk>',
        ShareGraphicLikeUpdateAPIView.as_view()
    ),
    re_path(
        r'user_course_all_list/(?P<term>.+)/$',
        UserCourseListAPIView.as_view()
    ),
    path(
        'user_course_item_update/<int:pk>',
        UserCourseItemUpdateAPIView.as_view()
    ),
    path(
        'create_user_course_remarks_item/',
        UserCourseRemarksCreateAPIView.as_view()
    ),
    path(
        'delete_user_course_remarks_item/<int:pk>',
        UserCourseRemarksDestroyAPIView.as_view()
    ),
    path(
        'get_user_course_remarks_item/<int:pk>',
        UserCourseRemarksRetrieveAPIView.as_view()
    ),
    path(
        'get_apply_course_item/<int:pk>',
        ApplyCourseRetrieveAPIView.as_view()
    ),
    path(
        'get_feedback_form_item/<int:pk>',
        FeedbackFormRetrieveAPIView.as_view()
    ),
    path(
        'get_teacher_item_info_form/<int:pk>',
        TeacherInfoFormRetrieveAPIView.as_view()
    )
]
