# Generated by Django 3.0.6 on 2020-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0002_auto_20200731_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecomment',
            name='moment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharelike',
            name='moment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sharelike',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sharelike',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sharelike',
            name='user_real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
