# Generated by Django 3.0.6 on 2020-06-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('head_img', models.URLField()),
            ],
        ),
    ]
