# Generated by Django 3.0.6 on 2020-06-09 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='create_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
