# Generated by Django 3.0.6 on 2020-08-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='mailBack',
        ),
    ]
