# Generated by Django 3.0.6 on 2020-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0002_remove_usercourse_mailback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='mail_back',
            field=models.BooleanField(default=False),
        ),
    ]
