# Generated by Django 3.0.6 on 2020-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0003_auto_20200731_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepic',
            name='moment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharepic',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharepic',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharepic',
            name='user_real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
