# Generated by Django 3.0.6 on 2020-08-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0003_usercourse_mail_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
