# Generated by Django 3.0.6 on 2020-08-25 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flourish', '0004_usercourse_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='remarks',
        ),
        migrations.CreateModel(
            name='UserCourseRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('fromPerson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toPerson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher')),
            ],
        ),
    ]
