# Generated by Django 3.0.6 on 2020-06-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0005_auto_20200610_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackpic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='infoform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
    ]
