# Generated by Django 3.0.6 on 2020-06-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0007_auto_20200610_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyCourses', to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='user_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_forms', to='flourish.UserCourse'),
        ),
        migrations.AlterField(
            model_name='feedbackpic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='feedback_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_units', to='flourish.FeedbackForm'),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='infoform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoForms', to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCourses', to='flourish.Teacher'),
        ),
    ]
