# Generated by Django 3.0.6 on 2020-07-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flourish', '0009_auto_20200707_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpic',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyCourses', to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackpic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='feedbackunit',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='infoform',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoForms', to='flourish.Teacher'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCourses', to='flourish.Teacher'),
        ),
    ]
