# Generated by Django 3.0.6 on 2020-06-09 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribeemail',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='subscribeemail',
            name='subscriber',
            field=models.ManyToManyField(related_name='subscribeEmails', to=settings.AUTH_USER_MODEL),
        ),
    ]
